import { OrderItem } from '.';

/**
 * Global app data
 */
export interface AppData{
    /** a JSON web token generated by the server once a user logins in */
    jwt: string;
    /** A list of items a user has added to their cart */
    cartItems: OrderItem[];
}

    /** A list of items a user has added to their cart */
export type ShoppingCartData = OrderItem[];

    /** a JSON web token generated by the server once a user logins in */
export type JWT = {token:string | null};