import { OrderItem } from '.';
import { AppHooks } from '../hooks';

/**
 * Global app data
 */


/** A list of items a user has added to their cart */
export type ShoppingCartData = OrderItem[];

/** a JSON web token generated by the server once a user logins in */
export type JWT = { token: string | null };

export interface AppState {
    /** a JSON web token generated by the server once a user logins in */
    jwt: JWT;
    /** A function to update the JWT */
    updateJWT:AppHooks.JWTUpdater;
    /** A list of items a user has added to their cart */
    cart: ShoppingCartData;
    /** A function to update the cart */
    updateCart:AppHooks.CartUpdater;
}

